/*
Copyright The Istio Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1alpha2 "istio-ecosystem/hsm-sds-server/pkg/apis/tcs/v1alpha2"
	scheme "istio-ecosystem/hsm-sds-server/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// QuoteAttestationsGetter has a method to return a QuoteAttestationInterface.
// A group's client should implement this interface.
type QuoteAttestationsGetter interface {
	QuoteAttestations(namespace string) QuoteAttestationInterface
}

// QuoteAttestationInterface has methods to work with QuoteAttestation resources.
type QuoteAttestationInterface interface {
	Create(ctx context.Context, quoteAttestation *v1alpha2.QuoteAttestation, opts v1.CreateOptions) (*v1alpha2.QuoteAttestation, error)
	Update(ctx context.Context, quoteAttestation *v1alpha2.QuoteAttestation, opts v1.UpdateOptions) (*v1alpha2.QuoteAttestation, error)
	UpdateStatus(ctx context.Context, quoteAttestation *v1alpha2.QuoteAttestation, opts v1.UpdateOptions) (*v1alpha2.QuoteAttestation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.QuoteAttestation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.QuoteAttestationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.QuoteAttestation, err error)
	QuoteAttestationExpansion
}

// quoteAttestations implements QuoteAttestationInterface
type quoteAttestations struct {
	client rest.Interface
	ns     string
}

// newQuoteAttestations returns a QuoteAttestations
func newQuoteAttestations(c *TcsV1alpha2Client, namespace string) *quoteAttestations {
	return &quoteAttestations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the quoteAttestation, and returns the corresponding quoteAttestation object, and an error if there is any.
func (c *quoteAttestations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.QuoteAttestation, err error) {
	result = &v1alpha2.QuoteAttestation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quoteattestations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of QuoteAttestations that match those selectors.
func (c *quoteAttestations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.QuoteAttestationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.QuoteAttestationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quoteattestations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested quoteAttestations.
func (c *quoteAttestations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("quoteattestations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a quoteAttestation and creates it.  Returns the server's representation of the quoteAttestation, and an error, if there is any.
func (c *quoteAttestations) Create(ctx context.Context, quoteAttestation *v1alpha2.QuoteAttestation, opts v1.CreateOptions) (result *v1alpha2.QuoteAttestation, err error) {
	result = &v1alpha2.QuoteAttestation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("quoteattestations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(quoteAttestation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a quoteAttestation and updates it. Returns the server's representation of the quoteAttestation, and an error, if there is any.
func (c *quoteAttestations) Update(ctx context.Context, quoteAttestation *v1alpha2.QuoteAttestation, opts v1.UpdateOptions) (result *v1alpha2.QuoteAttestation, err error) {
	result = &v1alpha2.QuoteAttestation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quoteattestations").
		Name(quoteAttestation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(quoteAttestation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *quoteAttestations) UpdateStatus(ctx context.Context, quoteAttestation *v1alpha2.QuoteAttestation, opts v1.UpdateOptions) (result *v1alpha2.QuoteAttestation, err error) {
	result = &v1alpha2.QuoteAttestation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quoteattestations").
		Name(quoteAttestation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(quoteAttestation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the quoteAttestation and deletes it. Returns an error if one occurs.
func (c *quoteAttestations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quoteattestations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *quoteAttestations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quoteattestations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched quoteAttestation.
func (c *quoteAttestations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.QuoteAttestation, err error) {
	result = &v1alpha2.QuoteAttestation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("quoteattestations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
