// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/private_key_providers/sgx/v3alpha/sgx.proto

package v3alpha

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SgxPrivateKeyMethodConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SgxPrivateKeyMethodConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SgxPrivateKeyMethodConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SgxPrivateKeyMethodConfigMultiError, or nil if none found.
func (m *SgxPrivateKeyMethodConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *SgxPrivateKeyMethodConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SgxLibrary

	// no validation rules for KeyLabel

	// no validation rules for UsrPin

	// no validation rules for SoPin

	// no validation rules for TokenLabel

	// no validation rules for KeyType

	if len(errors) > 0 {
		return SgxPrivateKeyMethodConfigMultiError(errors)
	}

	return nil
}

// SgxPrivateKeyMethodConfigMultiError is an error wrapping multiple validation
// errors returned by SgxPrivateKeyMethodConfig.ValidateAll() if the
// designated constraints aren't met.
type SgxPrivateKeyMethodConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SgxPrivateKeyMethodConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SgxPrivateKeyMethodConfigMultiError) AllErrors() []error { return m }

// SgxPrivateKeyMethodConfigValidationError is the validation error returned by
// SgxPrivateKeyMethodConfig.Validate if the designated constraints aren't met.
type SgxPrivateKeyMethodConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SgxPrivateKeyMethodConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SgxPrivateKeyMethodConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SgxPrivateKeyMethodConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SgxPrivateKeyMethodConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SgxPrivateKeyMethodConfigValidationError) ErrorName() string {
	return "SgxPrivateKeyMethodConfigValidationError"
}

// Error satisfies the builtin error interface
func (e SgxPrivateKeyMethodConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSgxPrivateKeyMethodConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SgxPrivateKeyMethodConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SgxPrivateKeyMethodConfigValidationError{}
